export default [
  {
    id: 1,
    title: 'IMP-EPMTP-S6-1',
    emplacement: 'Apothicaire',
    color: '0',
    adresseip: '192.168.112.211',
    imageUrl: '/images/printers/hp3015.png',
    model: 'HP LaserJet P3015dn',
    description: 'Recto/Verso, Couloir salle 6',
    typeacces: 'Filaire, Wifi, Bureau Virtuel',
  },
  {
    id: 2,
    title: 'IMP-EPMTP-S6-2',
    emplacement: 'Apothicaire',
    color: '0',
    adresseip: '192.168.112.212',
    imageUrl: '/images/printers/hp3015.png',
    model: 'HP LaserJet P3015dn',
    description: 'Recto/Verso, Couloir salle 6',
    typeacces: 'Filaire, Wifi, Bureau Virtuel',
    url: 'https://www.vmware.com/fr/products/workstation-pro/workstation-pro-evaluation.html'
  },
  {
    id: 3,
    title: 'IMP-EPMTP-S6-3',
    emplacement: 'Apothicaire',
    color: '0',
    adresseip: '192.168.112.213',
    imageUrl: '/images/printers/hp3015.png',
    model: 'HP LaserJet P3015dn',
    description: 'Recto/Verso, Couloir salle 6',
    typeacces: 'Filaire, Wifi, Bureau Virtuel',
    url: 'https://www.vmware.com/fr/products/workstation-pro/workstation-pro-evaluation.html'
  },
  {
    id: 4,
    title: 'EPMTP-CV',
    emplacement: 'Croix-Verte',
    color: '1',
    adresseip: '192.168.165.110',
    model: 'HP LaserJet Pro M501dn',
    imageUrl: '/images/printers/hp3015.png',
    description: 'Recto/Verso, Salle repas Croix-Verte',
    typeacces: 'Bureau Virtuel',
  },
];
